[package]
name = "format-readers"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
commons = { workspace = true }
arrow = { workspace = true }
arrow-csv = { workspace = true }
arrow-json = { workspace = true }
parquet = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
async-stream = { workspace = true }
opendal = { workspace = true }
bytes = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
mime = { workspace = true }

[dev-dependencies]
opendal = { workspace = true, features = ["services-fs"] }
