FROM registry.access.redhat.com/ubi9/go-toolset:1.26 AS builder
ARG TARGETOS=linux
ARG TARGETARCH
ARG CGO_ENABLED=1

USER root
WORKDIR /workspace

COPY dc-controller/go.mod dc-controller/go.sum ./
RUN go mod download

COPY dc-controller/ .

RUN CGO_ENABLED=${CGO_ENABLED} GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    GOEXPERIMENT=strictfipsruntime \
    go build -a -o manager cmd/main.go

FROM registry.redhat.io/ubi9/ubi-minimal-pqc@sha256:8a842ac769de709143e4edeace516f2008dfdc431b64670ad3353fa323b44736
WORKDIR /

COPY --from=builder --chown=root:root --chmod=0555 /workspace/manager .
COPY config/ /manifests/

USER 1001:1001

ENTRYPOINT ["/manager"]
