name: HuggingFace
provider: huggingface
description: Hugging Face model and dataset hub
credentials_fields:
  - name: URI
    label: URI
    description: HuggingFace URI
    required: true
    type: string
  - name: TOKEN
    label: Token
    description: Huggingface token
    required: false
    type: string

