FROM docker.io/library/rust:1.96.0 AS builder

WORKDIR /src

COPY Cargo.toml Cargo.lock ./
COPY .cargo/ ./.cargo/
COPY libs/ ./libs/
COPY connectors/ ./connectors/
COPY services/ ./services/

RUN if [ -f /cachi2/cachi2.env ]; then . /cachi2/cachi2.env; fi && \
    cargo build --release -p rest-service && \
    cp target/release/rest-service /usr/local/bin/rest-service

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7@sha256:d91be7cea9f03a757d69ad7fcdfcd7849dba820110e7980d5e2a1f46ed06ea3b
WORKDIR /

COPY --from=builder --chown=root:root --chmod=0555 \
    /usr/local/bin/rest-service /app/rest-service

USER 1001:1001

ENTRYPOINT ["/app/rest-service"]
