FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:7fbeae18dc9476399f565e68255f602a3374ea8614ba3d14843565131a13ff93 AS builder

RUN microdnf install -y gcc gcc-c++ pkgconf make perl cargo \
    && microdnf clean all

WORKDIR /src

COPY Cargo.toml Cargo.lock ./
COPY .cargo/ ./.cargo/
COPY libs/ ./libs/
COPY connectors/ ./connectors/
COPY services/ ./services/

RUN if [ -f /cachi2/cachi2.env ]; then . /cachi2/cachi2.env; fi && \
    cargo build --release -p flight-service && \
    cp target/release/flight-service /usr/local/bin/flight-service

FROM registry.redhat.io/ubi9/ubi-minimal-pqc@sha256:8a842ac769de709143e4edeace516f2008dfdc431b64670ad3353fa323b44736
WORKDIR /

COPY --from=builder --chown=root:root --chmod=0555 \
    /usr/local/bin/flight-service /app/flight-service

USER 1001:1001

ENTRYPOINT ["/app/flight-service"]
